name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & push image
    
      run: |
        echo  "${{secrets.DOCKERPW}}" | docker login -u "saurabh04kumar" --password-stdin
        docker build -t webmagic1:v1 --file aba_Cucumberjava/Dockerfile .
        docker tag webmagic1:v1 saurabh04kumar/automationimage:v10
        docker push saurabh04kumar/automationimage:v10
  
      

