name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build t& push image
      working-directory: aba_Cucumberjava
      run: |
        echo  "${{secrets.DOCKERPW}}" | docker login -u "saurabh04kumar" --password-stdin
        docker image build -t webmagic1/flaskapp:v1
        docker push webmagic1/flaskapp:v1
      

