name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & push image
    
      run: |
        echo  "${{secrets.DOCKERPW}}" | docker login -u "saurabh04kumar" --password-stdin
        docker image build -t webmagic1:v1
        docker tag webmagic1:v1 saurabh04kumar/automationimage:v8
        docker push webmagic1/flaskapp:v1
      

